-- CREATE DATABASE [SoftUni]

-- USE [SoftUni]

-- TABLES WITH NO CONSTRAINTS [primary and foreign keys]

CREATE TABLE [Towns](
	-- [Id] INT PRIMARY KEY IDENTITY,
	[Id] INT IDENTITY NOT NULL,
	[Name] NVARCHAR(30) NOT NULL,
)

CREATE TABLE [Addresses](
	-- [Id] INT PRIMARY KEY IDENTITY,
	[Id] INT IDENTITY NOT NULL,
	[AddressText] NVARCHAR(200) NOT NULL,
	-- [TownId] INT FOREIGN KEY REFERENCES [Towns](Id) NOT NULL,
	[TownId] INT NOT NULL,
)

CREATE TABLE [Departments](
	-- [Id] INT PRIMARY KEY IDENTITY, 
	[Id] INT IDENTITY NOT NULL, 
	[Name] NVARCHAR(50) NOT NULL,
)

CREATE TABLE [Employees](
	-- [Id] INT PRIMARY KEY IDENTITY,
	[Id] INT IDENTITY NOT NULL,
	[FirstName] NVARCHAR(30) NOT NULL,
	[MiddleName] NVARCHAR(150),
	[LastName] NVARCHAR(30) NOT NULL,
	[JobTitle] NVARCHAR(50) NOT NULL,
	-- [DepartmentId] INT FOREIGN KEY REFERENCES [Departments](Id) NOT NULL,
	[DepartmentId] INT NOT NULL,
	[HireDate] DATE NOT NULL,
	[Salary] DECIMAL(6, 2) NOT NULL,
	-- [AddressId] INT FOREIGN KEY REFERENCES [Addresses](Id) NOT NULL,
	[AddressId] INT NOT NULL,
)


-- CONSTRAINTS [primary and foreign keys]

ALTER TABLE [Towns]
	ADD CONSTRAINT PK_Towns PRIMARY KEY (Id)

ALTER TABLE [Addresses]
	ADD CONSTRAINT PK_Addresses PRIMARY KEY (Id)

ALTER TABLE [Addresses]
	ADD CONSTRAINT FK_Addresses_TownId FOREIGN KEY (TownId) REFERENCES [Towns](Id)

ALTER TABLE [Departments]
	ADD CONSTRAINT PK_Departments PRIMARY KEY (Id)

ALTER TABLE [Employees]
	ADD CONSTRAINT PK_Employees PRIMARY KEY (Id)

ALTER TABLE [Employees]
	ADD CONSTRAINT FK_Employees_DepartmentId FOREIGN KEY (DepartmentId) REFERENCES [Departments](Id)

ALTER TABLE [Employees]
	ADD CONSTRAINT FK_Employees_AddressId FOREIGN KEY (AddressId) REFERENCES [Addresses](Id)